### ISSUE TITLE
[Request] Make The Lost Castle be a "harder end portal" structure

### ISSUE THREAD

**Issue by Reshirou** [Team-Remastered/The-Lost-Castle-Forge#1]
Possibly out of scope, but if not: The Lost Castle could replace Strongholds entirely by making the End Portal require a 4 - 4 - 4 - 4 frame setup, as apposed to vanilla 3 - 3 - 3 - 3

End Remastered has 15 eyes, plus the vanilla eye, for 16 total, as far as cross compatibility with that would go- which is the perfect number

eyes would have to always point towards the Castle though and not the vanilla Strongholds, but vanilla Strongholds wouldn't have to be removed so other mods that turn them into cooler dungeons with special loot can still work as intended

**Comment by Jack-Bagel** [comment]
I would like to keep the vanilla feel of the mod. I will add an achievement for when you get every eyes for people wanting a bigger challenge.
